import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/Layout/Header"
import Footer from "./components/Layout/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Next Js Production Grade Code ",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en" style={{ height: "100%" }}>
			<body className={inter.className + " flex flex-col min-h-screen bg-gray-100"}>
				<Header />
					<main className="container mx-auto px-4 flex-grow">
						{children}
					</main>
				<Footer />
			</body>
		</html>
	);
}
